version: '3.9'
services:
  app:
    image: node:19-alpine
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/diphda?schema=public
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    working_dir: /app
    command: sh -c "npm i && npm run dev"
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db:
  node_modules: